on:
  push:
    branches:
      - dev
name: 🚀 Deploy website to dev on push
  
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          npm run prod

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_DEV_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_DEV_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_DEV_CPANEL_REACT_PASSWORD }}
          protocol: ${{ secrets.GIT_DEV_CPANEL_REACT_PROTOCOL }}
          local-dir: ./dist/
